#!/usr/bin/env python

import argparse
from core.loader import Loader

parser = argparse.ArgumentParser(description='Thus - linux installer')
parser.add_argument(
    '--config', help='Config file location', default='/etc/thus.conf',
)
parser.add_argument(
    '--interface', help='User interface (text/gui)',
    default='qt'
)

args = parser.parse_args()

loader = Loader(args)
loader.run()
